dim: 19 # 棋盘维度
learning_rate: 5.0e-3 # 学习率
temp: 1.0 # 温控系数，控制输出动作概率进行softmax的加权 temp越小，概率分布的熵越小，也就是随机程度越小
c_puct: 5 # 控制playout时选动作Q与N的加权
buffer_size: 10000 # 经验池大小
batch_size: 256 # 取经验的batch大小
epochs: 2
playout_num: 400  # 在每步playout多少次
game_batch: 1000  # 共进行多少批次对局
game_batch_size: 1  # 每批游戏中，有几盘游戏用于存储经验，一个batch游戏结束后，开始训练
save_frequent: 1
eval_interval: 20
eval_num: 20
ratio: .55